Rails.application.config.assets.precompile += %w( gibberish_2.0.js )
Rails.application.config.assets.precompile += %w( coffee-script.js )
Rails.application.config.assets.precompile += %w( ace.js )
Rails.application.config.assets.precompile += %w( mode-coffee.js )
Rails.application.config.assets.precompile += %w( worker-coffee.js )
Rails.application.config.assets.precompile += %w( theme-monokai.js )
